<a href="https://colab.research.google.com/github/atg2431-alpha/neural_net_basics/blob/main/Neural_Net.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt

In [3]:
(X_train,Y_train) , (X_test,Y_test) = keras.datasets.mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [4]:
X_train.shape

(60000, 28, 28)

In [5]:
X_train[0].shape

(28, 28)

In [ ]:
for i in range(10):
  plt.matshow(X_train[i])

In [7]:
Y_train[:10]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4], dtype=uint8)

In [8]:
X_train = X_train / 255
X_test = X_test/255

In [9]:
X_train_flat = X_train.reshape(60000,784)
X_test_flat = X_test.reshape(len(X_test),784)

In [10]:
model = keras.Sequential([
    keras.layers.Dense(10,input_shape = (784,),activation = 'sigmoid')
])
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics = ['accuracy']

)
model.fit(X_train_flat,Y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.4689 - accuracy: 0.8773
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3041 - accuracy: 0.9147
Epoch 3/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2836 - accuracy: 0.9206
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2732 - accuracy: 0.9240
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2673 - accuracy: 0.9254


In [11]:
model.evaluate(X_test_flat,Y_test)

313/313 [==============================] - 1s 1ms/step - loss: 0.2686 - accuracy: 0.9244


[0.2685702443122864, 0.9243999719619751]

In [13]:
Y_pred = model.predict(X_test_flat)

313/313 [==============================] - 0s 1ms/step


In [21]:
np.argmax(Y_pred[1])

2

In [ ]:
plt.matshow(X_test[1])

In [22]:
Y_pred_labels = [np.argmax(i) for i in Y_pred]
Y_pred_labels[:5]

[7, 2, 1, 0, 4]

In [ ]:
for i in range(5):
  plt.matshow(X_test[i])

In [24]:
cm = tf.math.confusion_matrix(labels =Y_test,predictions = Y_pred_labels)
cm

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 961,    0,    1,    1,    0,    5,    7,    3,    2,    0],
       [   0, 1112,    3,    2,    0,    1,    4,    2,   11,    0],
       [   6,    9,  903,   15,   14,    5,   13,   13,   51,    3],
       [   3,    0,   16,  911,    0,   29,    2,   15,   29,    5],
       [   1,    1,    2,    1,  920,    0,   12,    4,   10,   31],
       [   8,    3,    1,   23,   11,  779,   18,    8,   34,    7],
       [  11,    3,    7,    1,    8,   10,  912,    2,    4,    0],
       [   1,    5,   20,    4,    8,    0,    0,  962,    3,   25],
       [   7,    6,    5,   16,    9,   21,    9,   14,  882,    5],
       [  11,    7,    1,   10,   29,    7,    0,   36,    6,  902]],
      dtype=int32)>

In [ ]:
import seaborn as sn
plt.figure(figsize=(10,7))
sn.heatmap(cm,annot=True,fmt='d')
plt.xlabel('Predicted')
plt.ylabel('Truth')
# it is used to check what model predicted wrong and right and how many times


In [28]:
model = keras.Sequential([
    keras.layers.Dense(100,input_shape = (784,),activation = 'relu'),
    keras.layers.Dense(10,activation='sigmoid')
])
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics = ['accuracy']

)
model.fit(X_train_flat,Y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.2739 - accuracy: 0.9231
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1237 - accuracy: 0.9638
Epoch 3/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0870 - accuracy: 0.9740
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0664 - accuracy: 0.9796
Epoch 5/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0538 - accuracy: 0.9834


In [29]:
model.evaluate(X_test_flat,Y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.0778 - accuracy: 0.9757


[0.0777873620390892, 0.9757000207901001]

In [32]:
# suppose you dont want to create flattened array
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28,28)),
    keras.layers.Dense(100,activation = 'relu'),
    keras.layers.Dense(10,activation='sigmoid')
])
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics = ['accuracy']

)
model.fit(X_train,Y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.2733 - accuracy: 0.9219
Epoch 2/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1268 - accuracy: 0.9632
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0876 - accuracy: 0.9738
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0667 - accuracy: 0.9801
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0526 - accuracy: 0.9842
